### ISSUE TITLE
No coverage reports with nyc@14

### ISSUE THREAD

**Issue by Miladiir** [welkie/node-boilerplate#45]
Hi, I am getting no coverage reports with nyc at version 14. If I pin it to the latest version of 13, I get the results as advertised. So to fix this project: `npm i --save-dev nyc@13`
I am kind of worried that this was not caught to be honest.

**Comment by welkie** [comment]
Confirmed after merging https://github.com/welkie/node-boilerplate/pull/46 that coverage report produced (on Windows 10 Pro).
